apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: auth-service
build:
  local:
    useBuildkit: true
  artifacts:
  - image: dev/auth-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
portForward:
- resourceType: service
  resourceName: auth-service
  port: 9090
